"""make username name unique

Revision ID: 89af2f7c052b
Revises: 7912b24d661c
Create Date: 2026-08-15 23:13:01.929951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89af2f7c052b'
down_revision: Union[str, Sequence[str], None] = '7912b24d661c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'auth_provider',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.alter_column('users', 'auth_provider',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'email'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
